-- 면접 예상 질문 캐시.
--
-- 사전 인터뷰(ai_interview)와 다른 것이다. ai_interview 는 자기소개서를 쓸 재료를 모으려고
-- AI 가 사용자에게 묻는 질문이고, 여기 담기는 것은 면접관이 물어볼 법한 질문을 미리 보여주는
-- 준비 자료다. 사용자 답변을 받지 않는다.
--
-- 장학금 단위로 둔다. 지원서(essay) 단위가 아니다:
--   · 자소서는 필요 없는데 면접만 보는 장학금이 있다(essay NOT_REQUIRED + interview REQUIRED).
--     지원서에 매달면 이 조합에서 질문을 못 준다.
--   · 같은 장학금을 준비하는 사용자끼리 질문이 같아도 무방하다. 한 번 만들어 공유하면
--     사용자 수만큼 LLM 을 부르지 않아도 된다.
--
-- 공고가 면접을 보지 않는다고 밝힌 장학금(interview_requirement = 'NOT_REQUIRED')에는
-- 만들지 않는다. null(언급 없음)은 판단 불가라 막지 않는다.

CREATE TABLE IF NOT EXISTS interview_prep_question (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scholarship_id BIGINT       NOT NULL REFERENCES scholarship (id),
    display_order  INTEGER      NOT NULL,
    question_text  TEXT         NOT NULL,
    -- 이 질문이 왜 나올 만한지. 사용자가 준비 방향을 잡도록 함께 보여준다.
    intent         TEXT,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL
);

-- 한 장학금에 같은 순번이 두 번 생기지 않게 막는다. 동시 요청으로 질문이 두 벌 만들어지는 것을
-- 애플리케이션 검사만으로 막을 수 없어 DB 에도 건다(ai_interview 에는 이 제약이 없어 같은 문제가 있다).
CREATE UNIQUE INDEX IF NOT EXISTS uk_interview_prep_scholarship_order
    ON interview_prep_question (scholarship_id, display_order);
