-- 면접 예상 질문에 답변 준비 자료를 붙인다.
--
-- 기존에는 질문(question_text)과 질문의도(intent)만 있었다. 기획 확정본은 질문 하나마다
-- 네 가지를 보여준다 — 질문의도 · 답변 Tip · 예시답변 · 구성 가이드(3단계).
--
-- 담는 위치를 둘로 나눈다.
--   · 질문·의도·Tip·구성가이드 → 장학금 단위. 사용자가 누구든 같은 내용이므로 한 번 만들어
--     공유한다(interview_prep_question 이 이미 장학금 단위다).
--   · 예시답변 → 지원서 단위. "작성한 자기소개서를 바탕으로" 만들어야 해서 사람마다 다르다.
--     자소서를 쓰지 않는 장학금(essay NOT_REQUIRED + interview REQUIRED)에서는 이 행이
--     아예 없고, 화면은 나머지만 보여주면 된다.

BEGIN;

-- 답변 Tip: "구체적인 경험을 들어 설명하면 신뢰도를 높일 수 있어요" 같은 한 문장
ALTER TABLE interview_prep_question
    ADD COLUMN IF NOT EXISTS answer_tip TEXT;

-- 구성 가이드: STEP1 강점제시 → STEP2 경험 설명 → STEP3 성장 및 활용
CREATE TABLE IF NOT EXISTS interview_prep_guide_step (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prep_question_id   BIGINT       NOT NULL REFERENCES interview_prep_question (id),
    step_order         INTEGER      NOT NULL,
    title              VARCHAR(40)  NOT NULL,
    description        TEXT         NOT NULL,
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL
);

-- 한 질문에 같은 순번이 두 번 생기지 않게 막는다. 동시 생성으로 가이드가 두 벌 쌓이는 것을
-- 애플리케이션 검사만으로는 막을 수 없다(interview_prep_question 과 같은 이유).
CREATE UNIQUE INDEX IF NOT EXISTS uk_prep_guide_question_order
    ON interview_prep_guide_step (prep_question_id, step_order);

-- 예시답변: 지원서(essay) × 질문 하나당 한 건
CREATE TABLE IF NOT EXISTS interview_prep_sample_answer (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    essay_id         BIGINT       NOT NULL REFERENCES essay (id),
    prep_question_id BIGINT       NOT NULL REFERENCES interview_prep_question (id),
    content          TEXT         NOT NULL,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_prep_sample_essay_question
    ON interview_prep_sample_answer (essay_id, prep_question_id);

COMMIT;

-- 장학금 기반 기본 예시답변.
--
-- 자기소개서를 받지 않는 장학금(essay NOT_REQUIRED + interview REQUIRED)에는 개인화할 재료가
-- 없다. 그렇다고 예시답변만 비워 두면 그 장학금을 준비하는 학생은 답변 예시를 아예 못 본다.
-- 그래서 공고 정보만으로 만든 일반 예시를 여기 함께 저장한다. 질문 생성과 같은 LLM 호출에서
-- 만들므로 추가 비용이 없다.
--
-- 자소서가 있으면 interview_prep_sample_answer(지원서 단위)의 개인화 답변이 이 값을 덮는다.

BEGIN;

ALTER TABLE interview_prep_question
    ADD COLUMN IF NOT EXISTS sample_answer TEXT;

COMMIT;
