-- LLM 파싱 이력
--
-- 대학 장학공지를 LLM 으로 파싱할 때마다 한 행을 남긴다. 남기는 이유는 셋이다.
--
-- 1) 정확도 측정 — 프롬프트를 고쳤을 때 나아졌는지 판단하려면 이전 결과가 있어야 한다.
--    prompt_version 없이 결과만 쌓으면 무엇과 비교하는지 알 수 없다.
-- 2) 실패 원인 추적 — 형식이 깨졌는지·잘렸는지·거부됐는지는 응답 원문을 봐야 안다.
--    성공은 정제 결과(parsed_json)를, 실패는 응답 원문(raw_response)을 저장한다.
--    실패 시엔 정제 객체가 애초에 만들어지지 않으므로 원문이 유일한 단서다.
-- 3) 원본 없이도 남는 기록 — raw_html 을 나중에 지우더라도 파싱 결과와 그때의 모델·프롬프트는 남는다.
--
-- raw_scholarship 에 FK 를 걸지 않는다. 원본이 지워져도 기록은 남아야 하기 때문이다.
--
-- ⚠️ 배포 전에 적용해야 한다. NoticeParseLog 엔티티가 새로 생기므로, 테이블이 없으면
--    ddl-auto=validate 가 실패해 애플리케이션이 뜨지 않는다.

BEGIN;

CREATE TABLE IF NOT EXISTS notice_parse_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_scholarship_id  BIGINT       NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    model_id            VARCHAR(60),
    prompt_version      VARCHAR(20),
    -- 본문이 상한(6,000자)을 넘어 잘린 채 호출됐는지. 성공한 건에도 남긴다:
    -- "잘린 채 성공" 이 가장 위험하다(뒷부분 제출서류·조건을 조용히 잃는다).
    body_truncated      BOOLEAN      NOT NULL DEFAULT FALSE,
    -- 자르기 전 정제 본문 길이. 상한을 올릴지, NOISE_SELECTOR 를 고칠지 판단하는 근거.
    body_length         INTEGER,
    parsed_json         TEXT,
    raw_response        TEXT,
    error_message       TEXT,
    created_at          TIMESTAMP(6) NOT NULL,

    -- 제약 이름을 Hibernate 생성 규칙과 맞춰, update 모드 환경에서 중복 생성되지 않게 한다.
    CONSTRAINT notice_parse_log_status_check
        CHECK (status IN ('PENDING', 'PARSED', 'SKIPPED', 'FAILED'))
);

-- 한 원본의 이력을 최신순으로 훑는다(프롬프트 개정 전후 비교).
CREATE INDEX IF NOT EXISTS idx_notice_parse_log_raw
    ON notice_parse_log (raw_scholarship_id, id DESC);

-- 잘린 건수 집계. 상한을 올릴지 판단할 때 쓴다.
CREATE INDEX IF NOT EXISTS idx_notice_parse_log_truncated
    ON notice_parse_log (body_truncated) WHERE body_truncated;

COMMIT;

-- 검증
--   SELECT status, count(*), count(*) FILTER (WHERE body_truncated) AS 잘림
--   FROM notice_parse_log GROUP BY status;
