-- 중복 장학금 병합 후보 큐
--
-- LLM 이 중복으로 판단한 장학금 쌍을 담아두고, 사람이 승인해야 실제 병합이 일어나게 한다.
-- 병합은 되돌리기 어렵다(스크랩·자소서 등 사용자 데이터가 다른 장학금으로 옮겨간다).
-- 오판으로 멀쩡한 장학금을 지우는 사고를 막기 위해 관문을 하나 둔 것이다.
--
-- primary_scholarship_id   남길 쪽
-- duplicate_scholarship_id 병합 후 소프트 삭제할 쪽
--
-- 같은 쌍이 배치마다 다시 올라오지 않도록 (primary, duplicate) 에 유니크를 건다.
-- REJECTED 로 남은 쌍도 행이 유지되므로 "중복 아님" 판정이 재실행에도 유지된다.
--
-- 운영은 ddl-auto=validate 이므로 이 마이그레이션 없이 배포하면 기동이 실패한다.

BEGIN;

CREATE TABLE IF NOT EXISTS scholarship_merge_candidate (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primary_scholarship_id   BIGINT       NOT NULL,
    duplicate_scholarship_id BIGINT       NOT NULL,
    status                   VARCHAR(20)  NOT NULL,
    reason                   TEXT,
    note                     TEXT,
    reviewed_by              UUID,
    reviewed_at              TIMESTAMP(6),
    created_at               TIMESTAMP(6) NOT NULL,
    updated_at               TIMESTAMP(6) NOT NULL,

    CONSTRAINT uk_merge_candidate_pair
        UNIQUE (primary_scholarship_id, duplicate_scholarship_id),
    CONSTRAINT fk_merge_candidate_primary
        FOREIGN KEY (primary_scholarship_id) REFERENCES scholarship (id),
    CONSTRAINT fk_merge_candidate_duplicate
        FOREIGN KEY (duplicate_scholarship_id) REFERENCES scholarship (id),
    -- 자기 자신과의 병합은 성립하지 않는다.
    CONSTRAINT ck_merge_candidate_not_self
        CHECK (primary_scholarship_id <> duplicate_scholarship_id),
    -- 제약 이름을 Hibernate 생성 규칙과 맞춰, update 모드 환경에서 중복 생성되지 않게 한다.
    CONSTRAINT scholarship_merge_candidate_status_check
        CHECK (status IN ('PENDING', 'REJECTED', 'MERGED'))
);

-- 어드민 화면이 승인 대기 목록을 상태로 필터링해 조회한다.
CREATE INDEX IF NOT EXISTS idx_merge_candidate_status
    ON scholarship_merge_candidate (status, id);

COMMIT;
